name: first workflow ech test
on: push

jobs:
  echo_job:
    runs-on: ubuntu_latest
    steps:
      - name: echo test
        run: echo "hellloooo githubactionssssfdfdf"
      - name: eecond echo
        run: echo "byeeeee"